app = 'dynamic-classifier'
primary_region = 'mad'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[experimental]
  kill_signal = "SIGINT"
  kill_timeout = "5s"
